'use strict';
const cases={
 tennis:{tag:'SELECTED SUCCESS',title:'A trajectory that stays close to GT',description:'Panoptic tennis, point 364. Selected for low absolute 3D error across the active trajectory; maximum error is approximately 1.6 cm, including the query frame.',mv:8.31,ours:0.88},
 dex:{tag:'SELECTED SUCCESS',title:'Tracking a manipulated object',description:'DexYCB 20200709-subject-01 / 141754, point 365. Selected for the largest mean 3D error reduction among eligible points in this scene.',mv:33.205,ours:1.421},
 typical:{tag:'WITHIN-SCENE MEDIAN',title:'The middle of this scene’s ranked points',description:'Panoptic tennis, point 359. Median mean 3D error reduction among eligible points in this scene; not a median over the complete benchmark.',mv:10.318809,ours:1.101947},
 failure:{tag:'SELECTED FAILURE',title:'When refinement moves away from the target',description:'Panoptic juggle, point 201. Selected for the least mean 3D improvement among eligible points in this scene. The baseline is more accurate here.',mv:5.82,ours:40.35}
};
let cohort='original',results=[];
function pressed(button,attribute){document.querySelectorAll('['+attribute+']').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
function caseUpdate(name,play=false){const c=cases[name],v=document.getElementById('case-video');['tag','title','description'].forEach(k=>document.getElementById('case-'+k).textContent=c[k]);document.getElementById('mv-error').innerHTML=c.mv.toFixed(2)+' <small>cm</small>';document.getElementById('our-error').innerHTML=c.ours.toFixed(2)+' <small>cm</small>';v.pause();v.poster='assets/'+name+'-poster.jpg';v.querySelector('source').src='assets/'+name+'.mp4';v.load();if(play&&!matchMedia('(prefers-reduced-motion: reduce)').matches)v.play().catch(()=>{});}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{pressed(b,'data-case');caseUpdate(b.dataset.case,true)}));
const methods=[['Initialization','Triangulated initialization',''],['MVTracker + DUSt3R','MVTracker + DUSt3R',''],['Primary pseudo-selected TTO','DINO-MVTrack','Pseudo-selected · primary'],['GT-AJ-selected TTO','DINO-MVTrack','GT-best saved step · diagnostic']];
const datasets=['panoptic','dexycb','kubric'];
function format(value){return value===null||value===undefined?'—':(100*value).toFixed(2)}
function renderResults(){const lookup=(method,ds)=>results.find(r=>r.cohort===cohort&&r.dataset===ds&&r.method===method)||{};document.getElementById('results-body').innerHTML=methods.map(([key,label,sub],i)=>'<tr class="'+(i===3?'oracle-row':i===2?'ours-row':'')+'"><th scope="row">'+label+(sub?'<span class="row-sub">'+sub+'</span>':'')+'</th>'+datasets.map(ds=>{const r=lookup(key,ds);return '<td>'+format(r.aj3d)+'</td><td>'+format(r.mte_m)+'</td>'}).join('')+'</tr>').join('');document.getElementById('results-2d').innerHTML=[['CoTracker3 online','CoTracker3 online · 2D teacher',''],...methods.slice(1)].map(([key,label,sub])=>'<tr'+(key==='GT-AJ-selected TTO'?' class="oracle-row"':'')+'><th scope="row">'+label+(sub?'<span class="row-sub">'+sub+'</span>':'')+'</th>'+datasets.map(ds=>'<td>'+format(lookup(key,ds).aj2d_256)+'</td>').join('')+'</tr>').join('');}
document.querySelectorAll('[data-cohort]').forEach(b=>b.addEventListener('click',()=>{cohort=b.dataset.cohort;pressed(b,'data-cohort');document.getElementById('cohort-description').textContent=cohort==='mixed'?'GT-conditioned quality/diversity point set, with CoTracker3 online pseudo tracks and re-triangulated initialization. The point set uses GT reliability signals; this is not a point-selection-only ablation.':'Original fixed point set, with CoTracker3 online pseudo tracks and fixed initialization. The point set and benchmark inputs retain their original GT dependencies.';renderResults()}));
fetch('assets/results.json').then(r=>{if(!r.ok)throw Error('Results unavailable');return r.json()}).then(x=>{results=x;renderResults()}).catch(()=>{document.getElementById('results-body').innerHTML='<tr><td colspan="7">Could not load results. Please use the downloadable CSV.</td></tr>'});
fetch('assets/provenance.json').then(r=>r.json()).then(p=>{p.cases.forEach(c=>{cases[c.id].mv=c.mean_3d_error_cm.mvtracker;cases[c.id].ours=c.mean_3d_error_cm.dino_mvtrack});const active=document.querySelector('[data-case].active');const c=cases[active.dataset.case];document.getElementById('mv-error').innerHTML=c.mv.toFixed(2)+' <small>cm</small>';document.getElementById('our-error').innerHTML=c.ours.toFixed(2)+' <small>cm</small>'}).catch(()=>{});
for(let i=0;i<8;i++){const el=document.createElement('div');el.className='window';el.style.left=(i*18/150*100)+'%';el.style.top=(i*15+5)+'px';el.title='Frames '+i*18+'–'+(i*18+23);document.getElementById('windows').append(el)}
// Start only by explicit user interaction. Pause video when it leaves the viewport.
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)e.target.pause()}),{threshold:.05});document.querySelectorAll('video').forEach(v=>observer.observe(v))}
const scenes={tennis:{file:'long-sequence',poster:'long-poster',caption:'Panoptic tennis · six GT-selected points · 150 frames · historical CoTracker offline teacher · independent clip TTO.'},dex:{file:'gallery-dex',poster:'gallery-dex-poster',caption:'DexYCB · 20200709-subject-01 / 141754 · four moving points · CoTracker3 online teacher · pseudo-selected model.'},kubric:{file:'gallery-kubric',poster:'gallery-kubric-poster',caption:'Kubric · scene 6 · four moving points · CoTracker3 online teacher · pseudo-selected model.'}};
document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>{pressed(b,'data-scene');const s=scenes[b.dataset.scene],v=document.getElementById('gallery-video');v.pause();v.poster='assets/'+s.poster+'.jpg';v.querySelector('source').src='assets/'+s.file+'.mp4';document.getElementById('gallery-caption').textContent=s.caption;v.load();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)v.play().catch(()=>{})}));
const featureCaptions={'cross-view':'Panoptic tennis, point 16 · frame 22 · camera 14 → camera 1. The DINO patch-center peak is 8.19 px from GT; the selected tracker-feature peak is 408.24 px away. All five feature variants are shown.',reappearance:'Kubric scene 1, point 406 · source frame 0 → target frame 14 · view 2. After annotated invisibility in frames 8–13, the DINO patch-center peak is 5.34 px from GT; the selected tracker-feature peak is 12.83 px away.'};
document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{pressed(b,'data-feature');const src='assets/feature-'+b.dataset.feature+'.png';document.getElementById('feature-image').src=src;document.getElementById('feature-link').href=src;document.getElementById('feature-caption').textContent=featureCaptions[b.dataset.feature]}));
let ablationData=null,ablationScene='panoptic';const armLabels={full:'Full reference',without_dino:'Without DINO',frozen_fnet:'Frozen tracker encoder',residual_fusion:'Residual fusion'};const ablationText={panoptic:['Panoptic / tennis','The full reference has higher AJ than the three variants on this development clip. Removing DINO also changes the view weights, so this is evidence about the combined branch.'],dexycb:['DexYCB / 145653','Residual fusion has the highest AJ on this clip. Freezing the tracker encoder gives the lowest MTE. The preferred variant therefore depends on the metric.'],kubric:['Kubric / scene 1','The variant without DINO has the highest AJ and lowest MTE on this clip. This counterexample prevents a claim of uniform improvement from the semantic branch.']};
function renderAblation(){if(!ablationData)return;document.getElementById('ablation-title').textContent=ablationText[ablationScene][0];document.getElementById('ablation-reading').textContent=ablationText[ablationScene][1];document.getElementById('ablation-bars').innerHTML=Object.entries(armLabels).map(([arm,label])=>{const r=ablationData.rows.find(r=>r.dataset===ablationScene&&r.arm===arm);return '<div class="ablation-bar"><div><span>'+label+'</span><b>'+r.aj3d_percent.toFixed(2)+'% <small>MTE '+r.mte_cm.toFixed(2)+' cm</small></b></div><div class="bar-track" aria-hidden="true"><span style="width:'+r.aj3d_percent+'%"></span></div></div>'}).join('')}
fetch('assets/ablations.json').then(r=>{if(!r.ok)throw Error('Ablation data unavailable');return r.json()}).then(x=>{ablationData=x;renderAblation()}).catch(()=>{document.getElementById('ablation-reading').textContent='Could not load the chart. The complete development results are available in the downloadable CSV.'});
document.querySelectorAll('[data-ablation]').forEach(b=>b.addEventListener('click',()=>{pressed(b,'data-ablation');ablationScene=b.dataset.ablation;renderAblation()}));
document.getElementById('copy-bibtex').addEventListener('click',async()=>{const node=document.getElementById('bibtex-code'),status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(node.textContent+'\n');status.textContent='BibTeX copied.'}catch{const range=document.createRange();range.selectNodeContents(node);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);status.textContent='Citation selected. Use your browser’s copy command, or download the .bib file.'}});
// Keep playback focused on the selected example.
document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));
